version: '3'

services:
  nginx:
    image: nginx:1.15.7
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx
      - ./www:/home/bitrix/ext_www/oni-systems.com
      - ./www/errors_page:/var/www/errors_page
      - ./www/log/nginx:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro

  httpd:
    image: httpd:2.4
    expose:
      - 8887
    volumes:
      - ./httpd/conf:/usr/local/apache2/conf
      - ./www/htdocs:/home/bitrix/ext_www/oni-systems.com
      - ./www/log/httpd:/usr/local/apache2/logs
      - ./httpd/run:/usr/local/apache2/run/
      - /etc/localtime:/etc/localtime:ro